import { StyleSheet, Platform } from "react-native";
const THEME_PURPLE = '#37474F'; // Dark gray color for the theme
const LIGHT_BG = '#fff';
const LIGHT_GRAY = '#f6f8fa';
const BORDER = '#e5e7eb';
const TEXT_GRAY = '#6b7280';
export const addproductStyles = StyleSheet.create({
    
  label: {
    fontWeight: "600",
    color: "#22223b",
    fontSize: 15,
    marginBottom: 6,
    marginTop: 18,
  },
  inputBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginBottom: 8,
  },
pickerContainer: {
  borderWidth: 1,
  borderColor: '#e5e7eb',
  backgroundColor: LIGHT_BG,
  borderRadius: 8,
  // overflow: 'hidden', // Remove this
  minHeight: 50, // Ensure enough space
  justifyContent: 'center',
  minWidth: 180,
},
picker: {
  height: 50,
  width: '100%',
  color: THEME_PURPLE,
},
pickerItem: {
  fontSize: 14,
  color: THEME_PURPLE,
},


  input: {
    fontSize: 18,
    color: "#22223b",
    flex: 1,
    padding: 0,
    backgroundColor: "transparent",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  gridItem: {
    width: "30%",
    aspectRatio: 1.1,
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    padding: 8,
  },
  gridLabel: {
    fontSize: 13,
    color: "#22223b",
    marginTop: 6,
    fontWeight: "500",
    textAlign: "center",
  },
  paymentGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  paymentGridItem: {
    width: "48%",
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    alignItems: "flex-start",
    justifyContent: "center",
    marginBottom: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
  },
  paymentGridLabel: {
    fontSize: 14,
    color: "#22223b",
    fontWeight: "500",
    marginLeft: 10,
  },
  notesInput: {
    backgroundColor: "#fff",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: "#22223b",
    minHeight: 60,
    marginBottom: 18,
    marginTop: 4,
    textAlignVertical: "top",
  },
  addBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#37474F",
    borderRadius: 10,
    paddingVertical: 14,
    justifyContent: "center",
    marginTop: 10,
    marginBottom: 20,
  },
  addBtnText: {
    color: "#fff",
    fontWeight: "700",
  },
  headerWrapper: {
    width: "100%",
    backgroundColor: "white",
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    paddingBottom: 8,
    marginBottom: 8,
    zIndex: 10,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingTop: Platform.OS === "ios" ? 48 : 24,
    paddingBottom: 12,
  },
  iconBox: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  walletIconBg: {
    width: 32,
    height: 32,
    backgroundColor: "#37474F",
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#1f2937",
    fontFamily: "System",
    letterSpacing: 0.5,
  },
});