import { StyleSheet,Platform } from 'react-native';
const THEME_PURPLE = '#37474F'; // Dark gray color for the theme
const LIGHT_BG = '#fff';
const LIGHT_GRAY = '#f6f8fa';
const BORDER = '#e5e7eb';
const TEXT_GRAY = '#6b7280';
export const profileStyles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: THEME_PURPLE,
    paddingHorizontal: 18,
    paddingTop: Platform.OS === 'ios' ? 48 : 18,
    paddingBottom: 18,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  headerTitle: {
    color: LIGHT_BG,
    fontSize: 20,
    fontWeight: '700',
    marginLeft: 4,
    letterSpacing: 0.5,
  },
  userCard: {
    backgroundColor: LIGHT_BG,
    marginHorizontal: 14,
    marginTop: -32,
    borderRadius: 14,
    padding: 18,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
    zIndex: 1,
  },
  avatarCircle: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#ede9fe',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 0,
    marginLeft: -45,
    borderWidth: 2,
    borderColor: LIGHT_BG,
  },
  userName: {
    fontSize: 20,
    fontWeight: '700',
    color: '#22223b',
    marginTop: 0,
  },
  userEmail: {
    fontSize: 13,
    color: TEXT_GRAY,
    marginTop: 1,
  },
  profileActions: {
    flexDirection: 'row',
    marginTop: 18,
    width: '100%',
    justifyContent: 'space-between',
  },
  editBtn: {
    backgroundColor: THEME_PURPLE,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
  },
  editBtnText: {
    color: LIGHT_BG,
    fontWeight: '600',
    fontSize: 14,
  },
  logoutBtn: {
    borderColor: BORDER,
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 18,
    backgroundColor: LIGHT_BG,
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoutBtnText: {
    color: '#22223b',
    fontWeight: '600',
    fontSize: 14,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#22223b',
    marginTop: 28,
    marginLeft: 18,
    marginBottom: 10,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 14,
    marginBottom: 10,
    gap: 8,
  },
  summaryCard: {
    flex: 1,
    backgroundColor: LIGHT_BG,
    borderRadius: 12,
    padding: 16,
    alignItems: 'flex-start',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
    minWidth:0
  },
  
  summaryLabel: {
    fontSize: 13,
    color: TEXT_GRAY,
    fontWeight: '500',
  },
  summaryValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#22223b',
    marginTop: 2,
  },
  summarySub: {
    fontSize: 12,
    color: TEXT_GRAY,
    marginTop: 2,
  },
  favCategoryCard: {
    backgroundColor: LIGHT_BG,
    borderRadius: 12,
    marginHorizontal: 14,
    marginBottom: 18,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  favCategoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  favCategoryLabel: {
    fontSize: 13,
    color: TEXT_GRAY,
    fontWeight: '500',
    flex: 1,
  },
  favCategoryIconBox: {
    backgroundColor: '#ede9fe',
    borderRadius: 8,
    padding: 6,
    marginLeft: 8,
  },
  favCategoryTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#22223b',
    marginTop: 2,
  },
  favCategorySub: {
    fontSize: 12,
    color: TEXT_GRAY,
    marginTop: 2,
  },
  recentHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 14,
    marginTop: 18,
    marginBottom: 6,
  },
  viewAll: {
    color: THEME_PURPLE,
    fontWeight: '600',
    fontSize: 13,
  },
  activityCard: {
    backgroundColor: LIGHT_BG,
    borderRadius: 12,
    marginHorizontal: 14,
    marginBottom: 18,
    padding: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  activityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    paddingHorizontal: 4,
  },
  activityIconBoxGreen: {
    backgroundColor: '#d1fae5',
    borderRadius: 8,
    padding: 6,
    marginRight: 10,
  },
  activityIconBoxBlue: {
    backgroundColor: '#dbeafe',
    borderRadius: 8,
    padding: 6,
    marginRight: 10,
  },
  activityIconBoxPurple: {
    backgroundColor: '#ede9fe',
    borderRadius: 8,
    padding: 6,
    marginRight: 10,
  },
  activityTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#22223b',
  },
  activitySub: {
    fontSize: 12,
    color: TEXT_GRAY,
    marginTop: 2,
  },
  activityAmountNeg: {
    fontSize: 15,
    fontWeight: '700',
    color: '#ef4444',
    marginLeft: 8,
  },
});