import { StyleSheet,Platform } from "react-native";
export const signupStyles = StyleSheet.create({
  container: {
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 24,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 18,
    width: "100%",
    maxWidth: 370,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
    marginBottom: 18,
  },
  title: {
    fontSize: 22,
    fontWeight: "700",
    color: "#22223b",
    marginBottom: 2,
    alignSelf: "flex-start",
  },
  subtitle: {
    color: "#6b7280",
    fontSize: 15,
    marginBottom: 18,
    alignSelf: "flex-start",
  },
  inputLabel: {
    color: "#6b7280",
    fontWeight: "600",
    marginBottom: 4,
    marginTop: 12,
    fontSize: 14,
    alignSelf: "flex-start",
  },
  input: {
    backgroundColor: "#f3f4f6",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: "#22223b",
    marginBottom: 8,
  },
  helperText: {
    color: "#6b7280",
    fontSize: 12,
    marginBottom: 2,
    alignSelf: "flex-start",
    marginLeft: 2,
  },
  loginBtn: {
    backgroundColor: "#37474F",
    borderRadius: 8,
    paddingVertical: 13,
    alignItems: "center",
    marginTop: 16,
    marginBottom: 2,
    width: "100%",
    maxWidth: 370,
  },
  loginBtnText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    maxWidth: 370,
    marginVertical: 18,
  },
  divider: {
    flex: 1,
    height: 1,
    backgroundColor: "#e5e7eb",
  },
  orText: {
    marginHorizontal: 10,
    color: "#6b7280",
    fontWeight: "600",
    fontSize: 13,
  },
  socialBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    paddingVertical: 12,
    paddingHorizontal: 18,
    width: "100%",
    maxWidth: 370,
    marginBottom: 10,
  },
  socialBtnText: {
    color: "#22223b",
    fontWeight: "600",
    fontSize: 15,
  },
});